#!/bin/sh
# clipbridge: wl-copy shim
# When clip-route says you are on your machine (the client), the text (stdin, or the text
# arguments) goes to your machine's clipboard through clipbridge-ssh. Otherwise: the
# real wl-copy.
REAL=${CLIPBRIDGE_REAL_WL_COPY:-/usr/bin/wl-copy}
BIN=$(dirname "$0")

if "$BIN/clip-route"; then
  sel=clipboard; clear=0; words=""
  while [ $# -gt 0 ]; do
    case "$1" in
      -p|--primary) sel=primary ;;
      -c|--clear) clear=1 ;;
      -t|--type|-s|--seat) shift ;;           # options that take a value
      --) shift; words="$*"; break ;;
      -*) ;;                                   # other flags do not matter here
      *) words="$*"; break ;;                  # text given as arguments
    esac
    shift
  done
  if [ "$clear" = 1 ]; then printf '' | "$BIN/clipbridge-ssh" set "$sel"; exit $?
  elif [ -n "$words" ]; then printf '%s' "$words" | "$BIN/clipbridge-ssh" set "$sel"; exit $?
  else exec "$BIN/clipbridge-ssh" set "$sel"   # stdin passes straight through
  fi
fi
exec "$REAL" "$@"
